server:
  port: 8080

spring:
  cloud:
    sentinel:
      transport:
        dashboard: sentinel:8858
    gateway:
      discovery:
        locator:
          enabled: true # Enable service discovery based routing
          lower-case-service-id: true # Use lowercase service IDs
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.client: DEBUG
